export default {
  products: [
    {
      _id: '1',
      name: 'Philodendron Moonlight',
      image: '/images/plant/phil.jpeg',
      price: 14,
    },
    {
      _id: '2',
      name: 'Sansevieria Superba',
      image: '/images/plant/sans.jpeg',
      price: 14,
    },
    {
      _id: '3',
      name: 'ZZ Plant Zenzi',
      image: '/images/plant/zz.png',
      price: 18,
    },
    {
      _id: '4',
      name: 'Ficus Benjamina Variegated',
      image: '/images/plant/benjamina.jpeg',
      price: 22,
    },
    {
      _id: '5',
      name: 'Ficus Trangularis',
      image: '/images/plant/ficusT.jpeg',
      price: 225,
    },
    {
      _id: '6',
      name: 'Ficus Altissima',
      image: '/images/plant/ficusA.jpeg',
      price: 32,
    },
    {
      _id: '7',
      name: 'Philodendron Prince of Orange',
      image: '/images/plant/philP.jpeg',
      price: 14,
    },
    {
      _id: '8',
      name: 'Aglaonema Cutlass',
      image: '/images/plant/agla.jpeg',
      price: 26,
    },
    {
      _id: '9',
      name: 'Croton Plant',
      image: '/images/plant/croton.jpeg',
      price: 7,
    },
    {
      _id: '10',
      name: 'Philodendron Cordatum',
      image: '/images/plant/philC.jpeg',
      price: 8,
    },
    {
      _id: '11',
      name: 'Yucca',
      image: '/images/plant/yucca.jpeg',
      price: 24,
    },
    {
      _id: '12',
      name: 'Aglaonema Lady Valentine',
      image: '/images/plant/aglaL.jpeg',
      price: 18,
    },
    {
      _id: '13',
      name: 'Aglaonema',
      image: '/images/plant/agla.jpeg',
      price: 14,
    },
    {
      _id: '14',
      name: 'Monstera Deliciosa',
      image: '/images/plant/mon.jpeg',
      price: 12,
    },
    {
      _id: '15',
      name: 'Ficus Elastica Ruby',
      image: '/images/plant/ficusE.jpeg',
      price: 10,
    },
    {
      _id: '16',
      name: 'Ficus Elastica Tineke',
      image: '/images/plant/ficusT.jpeg',
      price: 9,
    },

    {
      _id: '17',
      name: 'Calathea Makoyana',
      image: '/images/plant/calathea.jpeg',
      price: 15,
    },

    {
      _id: '18',
      name: 'Ficus Ginseng',
      image: '/images/plant/ficusG.jpeg',
      price: 16,
    },

    {
      _id: '19',
      name: 'Calathea Lancifolia',
      image: '/images/plant/calatheaL.jpeg',
      price: 15,
    },

    {
      _id: '20',
      name: 'Ficus Audrey',
      image: '/images/plant/ficusA.jpeg',
      price: 36,
    },
    {
      _id: '21',
      name: 'Money Tree',
      image: '/images/plant/money.jpeg',
      price: 16,
    },
    {
      _id: '22',
      name: 'Hoya Publicalyx',
      image: '/images/plant/hoya.jpeg',
      price: 14,
    },
    {
      _id: '23',
      name: 'Calathea Ornata',
      image: '/images/plant/calatheaO.jpeg',
      price: 8,
    },
    {
      _id: '24',
      name: 'Alocasia Polly',
      image: '/images/plant/polly.jpeg',
      price: 12,
    },
    {
      _id: '25',
      name: 'Philodendron Congo',
      image: '/images/plant/congo.jpeg',
      price: 15,
    },
    {
      _id: '26',
      name: 'Peace Lily',
      image: '/images/plant/peace.jpeg',
      price: 12,
    },
    {
      _id: '27',
      name: 'Philodendron Brasil',
      image: '/images/plant/brasil.jpeg',
      price: 8,
    },
    {
      _id: '28',
      name: 'Pilea Peperomioides',
      image: '/images/plant/pilea.jpeg',
      price: 12,
    },
    {
      _id: '29',
      name: 'Dieffenbachia Camille',
      image: '/images/plant/camille.jpeg',
      price: 9,
    },
    {
      _id: '30',
      name: 'Sansevieria Lurentii',
      image: '/images/plant/sanse.jpeg',
      price: 14,
    },
    {
      _id: '31',
      name: 'Cataractarum Palm',
      image: '/images/plant/palm.jpeg',
      price: 45,
    },
    {
      _id: '32',
      name: 'Pilea Glauca Aquamarine',
      image: '/images/plant/aquamarine.jpeg',
      price: 12,
    },
    {
      _id: '33',
      name: 'Asparagus Plumosus Fern',
      image: '/images/plant/fern.jpeg',
      price: 10,
    },
    {
      _id: '34',
      name: 'Diffenbachia Amoena Tropic Snow',
      image: '/images/plant/snow.jpeg',
      price: 12,
    },
    {
      _id: '35',
      name: 'Spider Plant Variegated',
      image: '/images/plant/spider.jpeg',
      price: 8,
    },
    {
      _id: '36',
      name: 'Alocasia Calidora',
      image: '/images/plant/calidora.jpeg',
      price: 26,
    },
    {
      _id: '37',
      name: 'Pothos Golden',
      image: '/images/plant/pothosG.jpeg',
      price: 10,
    },
    {
      _id: '38',
      name: 'Bird of Paradise',
      image: '/images/plant/bird.jpeg',
      price: 25,
    },
    {
      _id: '39',
      name: 'Fishhooks Senecio',
      image: '/images/plant/fishhook.jpeg',
      price: 9,
    },
    {
      _id: '40',
      name: 'Bird Nest Fern',
      image: '/images/plant/nest.jpeg',
      price: 11,
    },
  ],
};
